# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/geography',
                'doc_host': 'https://xiaochuany.github.io',
                'git_url': 'https://github.com/xiaochuany/geography',
                'lib_path': 'geography'},
  'syms': { 'geography.core': { 'geography.core.RGG': ('core.html#rgg', 'geography/core.py'),
                                'geography.core.RGG.__init__': ('core.html#rgg.__init__', 'geography/core.py'),
                                'geography.core.RGG.adj': ('core.html#rgg.adj', 'geography/core.py'),
                                'geography.core.RGG.cyclic': ('core.html#rgg.cyclic', 'geography/core.py'),
                                'geography.core.RGG.degree_distribution': ('core.html#rgg.degree_distribution', 'geography/core.py'),
                                'geography.core.RGG.distances': ('core.html#rgg.distances', 'geography/core.py'),
                                'geography.core.RGG.n_comp': ('core.html#rgg.n_comp', 'geography/core.py')}}}
