# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/geography',
                'doc_host': 'https://xiaochuany.github.io',
                'git_url': 'https://github.com/xiaochuany/geography',
                'lib_path': 'geography'},
  'syms': {'geography.core': {'geography.core.foo': ('core.html#foo', 'geography/core.py')}}}
